services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/app_development
    depends_on:
      - db
    # stdin_open: true
    # tty: true

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app_development
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  frontend_node_modules:
